# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['scbeditor2.py'],
            pathex=['G:\\DEV\\Python\\scbeditor2\\scbeditor2'],
            binaries=[],
            datas=[],
            hiddenimports=[],
            hookspath=[],
            runtime_hooks=[],
            excludes=[
                'altgraph',
                'astroid',
                'autocommand',
                'colorama',
                'contourpy',
                'cycler',
                'dill',
                'fonttools',
                'gitdb',
                'GitPython',
                'isort',
                'jaraco.context',
                'jaraco.functools',
                'jaraco.text',
                'kiwisolver',
                'matplotlib',
                'mccabe',
                'more-itertools',
                'numpy',
                'packaging',
                'pefile',
                'pip',
                'platformdirs',
                'Pmw',
                'pycodestyle',
                'pyinstaller',
                'pyinstaller-hooks-contrib',
                'pylint',
                'pymodbus',
                'pyparsing',
                'pypi',
                'pypiwin32',
                'python-dateutil',
                'pythonping',
                'pywin32',
                'pywin32-ctypes',
                'setuptools',
                'six',
                'smmap',
                'tomlkit',
                'ttkthemes',
                'ttkwidgets'
            ],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
            cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='scbeditor2',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          version='scbeditor2_version.txt',
          icon='ScbEditorII_T_512x512.ico')
